# SPDX-FileCopyrightText: 2026 Tim Christmann and Cloth NeXt contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Pure add-on update model: channels, states, index parsing, evaluation.

Cloth NeXt never self-updates. Installation goes exclusively through
Blender's own extension mechanism against the policy-defined channel
repositories (docs/RELEASE_POLICY.md sections 4, 10, and 12). This module
only determines and presents update *status*: Blender exposes no public API
to query a single package's update availability, so the status check reads
the channel ``index.json`` — the official format generated by the official
Blender tooling — from the fixed project URLs below. No other URL is ever
fetched, and nothing here downloads or replaces extension files.

No ``bpy`` import; every function is testable in plain Python.
"""

from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass
from enum import Enum, auto
from urllib.parse import urlsplit

from .addon_versions import AddonVersion, parse_version

EXTENSION_ID = "cloth_next"
RELEASES_PAGE_URL = "https://github.com/polyworks-art/Cloth_neXT/releases"
_ALLOWED_INDEX_HOST = "polyworks-art.github.io"
MAX_INDEX_SIZE = 4 * 1024 * 1024  # a channel index is tiny; anything larger is wrong


class UpdateChannel(Enum):
    STABLE = "https://polyworks-art.github.io/Cloth_neXT/stable/index.json"
    BETA = "https://polyworks-art.github.io/Cloth_neXT/beta/index.json"

    @property
    def index_url(self) -> str:
        return self.value

    @property
    def label(self) -> str:
        return self.name.capitalize()


def default_channel(installed: AddonVersion) -> UpdateChannel:
    """Beta when the installed version is itself a prerelease, else Stable."""
    return UpdateChannel.BETA if installed.is_prerelease else UpdateChannel.STABLE


class AddonUpdateState(Enum):
    NOT_CHECKED = auto()
    CHECKING = auto()
    UP_TO_DATE = auto()
    UPDATE_AVAILABLE = auto()
    REPOSITORY_NOT_CONFIGURED = auto()
    REPOSITORY_DISABLED = auto()
    SYNC_FAILED = auto()
    ONLINE_ACCESS_DISABLED = auto()
    INSTALL_BLOCKED = auto()
    INSTALLING = auto()
    RESTART_REQUIRED = auto()
    UNAVAILABLE = auto()
    ERROR = auto()


class AddonUpdateSession:
    """Mutable per-Blender-session check result; holds no threads or sockets."""

    def __init__(self) -> None:
        self.reset()

    def reset(self) -> None:
        self.state = AddonUpdateState.NOT_CHECKED
        self.latest: AddonVersion | None = None
        self.message = ""


def normalized_repo_url(url: str) -> str:
    return url.strip().rstrip("/")


def find_channel_repo(repos, channel: UpdateChannel) -> int | None:
    """Index of the repository whose remote URL is the channel URL, else None.

    A repository for the *other* channel never counts: Beta must not treat a
    Stable-only repository as its source, and vice versa.
    """
    wanted = normalized_repo_url(channel.index_url)
    for index, repo in enumerate(repos):
        remote_url = getattr(repo, "remote_url", "") or ""
        if normalized_repo_url(remote_url) == wanted:
            return index
    return None


def validate_index_url(url: str) -> None:
    parts = urlsplit(url)
    if parts.scheme != "https":
        raise ValueError(f"channel index requires https, got {url!r}")
    if parts.hostname != _ALLOWED_INDEX_HOST:
        raise ValueError(f"host {parts.hostname!r} is not the Cloth NeXt "
                         "channel host")


def fetch_channel_index(channel: UpdateChannel, *, timeout: float = 15.0,
                        open_url=None) -> dict:
    """Fetch and parse the channel index.json (bounded, fixed URL only)."""
    url = channel.index_url
    validate_index_url(url)
    if open_url is None:
        def open_url(target):  # pragma: no cover - exercised in integration
            request = urllib.request.Request(
                target, headers={"User-Agent": "ClothNeXt-UpdateCheck"})
            return urllib.request.urlopen(request, timeout=timeout)  # noqa: S310
    with open_url(url) as response:
        raw = response.read(MAX_INDEX_SIZE + 1)
    if len(raw) > MAX_INDEX_SIZE:
        raise ValueError("channel index exceeds the size limit")
    payload = json.loads(raw.decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("channel index must contain a JSON object")
    return payload


def parse_index_versions(payload: dict,
                         channel: UpdateChannel) -> tuple[AddonVersion, ...]:
    """Extract this extension's versions; enforce channel content rules.

    Stable may list only plain releases, Beta only prereleases
    (docs/RELEASE_POLICY.md section 4). A violation is an error, never a
    silently offered update.
    """
    data = payload.get("data")
    if not isinstance(data, list):
        raise ValueError("channel index has no 'data' package list")
    versions: list[AddonVersion] = []
    for entry in data:
        if not isinstance(entry, dict) or entry.get("id") != EXTENSION_ID:
            continue
        version = parse_version(str(entry.get("version")))
        if channel is UpdateChannel.STABLE and version.is_prerelease:
            raise ValueError(f"the stable channel offers prerelease {version}; "
                             "refusing the policy-violating index")
        if channel is UpdateChannel.BETA and not version.is_prerelease:
            raise ValueError(f"the beta channel offers stable release {version}; "
                             "refusing the policy-violating index")
        versions.append(version)
    return tuple(versions)


def evaluate_update(installed: AddonVersion,
                    available: tuple[AddonVersion, ...],
                    ) -> tuple[AddonUpdateState, AddonVersion | None]:
    if not available:
        return (AddonUpdateState.UNAVAILABLE, None)
    latest = max(available)
    if latest > installed:
        return (AddonUpdateState.UPDATE_AVAILABLE, latest)
    return (AddonUpdateState.UP_TO_DATE, latest)


def run_update_check(session: AddonUpdateSession, channel: UpdateChannel,
                     installed: AddonVersion,
                     fetch=fetch_channel_index) -> None:
    """Worker body: fetch, parse, evaluate; every failure becomes a visible
    ERROR state instead of a hang or a silent pass."""
    try:
        payload = fetch(channel)
        versions = parse_index_versions(payload, channel)
        state, latest = evaluate_update(installed, versions)
        session.latest = latest
        session.message = ("The channel index lists no Cloth NeXt entry yet."
                           if state is AddonUpdateState.UNAVAILABLE else "")
        session.state = state
    except Exception as exc:  # noqa: BLE001 — the UI must see every failure
        session.latest = None
        session.message = str(exc)
        session.state = AddonUpdateState.ERROR


def release_notes_url(version: AddonVersion | None) -> str:
    """Release notes are human documentation only, never an update source."""
    if version is None:
        return RELEASES_PAGE_URL
    return f"{RELEASES_PAGE_URL}/tag/v{version}"


STATUS_LABELS = {
    AddonUpdateState.NOT_CHECKED: "Not checked",
    AddonUpdateState.CHECKING: "Checking…",
    AddonUpdateState.UP_TO_DATE: "Up to date",
    AddonUpdateState.UPDATE_AVAILABLE: "Update available",
    AddonUpdateState.REPOSITORY_NOT_CONFIGURED: "Repository not configured",
    AddonUpdateState.REPOSITORY_DISABLED: "Repository disabled",
    AddonUpdateState.SYNC_FAILED: "Repository synchronization failed",
    AddonUpdateState.ONLINE_ACCESS_DISABLED: "Offline (online access disabled)",
    AddonUpdateState.INSTALL_BLOCKED: "Install blocked",
    AddonUpdateState.INSTALLING: "Installing…",
    AddonUpdateState.RESTART_REQUIRED: "Restart Blender required",
    AddonUpdateState.UNAVAILABLE: "No update information",
    AddonUpdateState.ERROR: "Error",
}


@dataclass(frozen=True, slots=True)
class UpdateSectionView:
    status_text: str
    message: str
    show_install: bool
    show_open_extensions: bool
    show_repo_setup: bool
    check_enabled: bool


def build_section_view(state: AddonUpdateState, latest: AddonVersion | None,
                       message: str) -> UpdateSectionView:
    status_text = STATUS_LABELS[state]
    if state is AddonUpdateState.UPDATE_AVAILABLE and latest is not None:
        status_text = f"{status_text}: {latest}"
    show_install = state is AddonUpdateState.UPDATE_AVAILABLE
    return UpdateSectionView(
        status_text=status_text,
        message=message,
        show_install=show_install,
        show_open_extensions=not show_install,
        show_repo_setup=state is AddonUpdateState.REPOSITORY_NOT_CONFIGURED,
        check_enabled=state not in (AddonUpdateState.CHECKING,
                                    AddonUpdateState.INSTALLING))
