# SPDX-FileCopyrightText: 2026 Tim Christmann and Cloth NeXt contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Pure add-on update model: channels, states, index parsing, evaluation.

Cloth NeXt never self-updates. Installation goes exclusively through
Blender's own extension mechanism against the policy-defined channel
repositories (docs/RELEASE_POLICY.md sections 4, 10, and 12). This module
only determines and presents update *status*: Blender exposes no public API
to query a single package's update availability, so the status check reads
the channel ``index.json`` — the official format generated by the official
Blender tooling — from the fixed project URLs below. No other URL is ever
fetched, and nothing here downloads or replaces extension files.

No ``bpy`` import; every function is testable in plain Python.
"""

from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass
from enum import Enum, auto
from urllib.parse import urlsplit

from .addon_versions import AddonVersion, parse_version
from .channel_policy import allowed_release_channels

EXTENSION_ID = "cloth_next"
RELEASES_PAGE_URL = "https://polyworks-art.github.io/Cloth_neXT/releases/"
_ALLOWED_INDEX_HOST = "polyworks-art.github.io"
MAX_INDEX_SIZE = 4 * 1024 * 1024  # a channel index is tiny; anything larger is wrong


class UpdateChannel(Enum):
    STABLE = "https://polyworks-art.github.io/Cloth_neXT/stable/index.json"
    BETA = "https://polyworks-art.github.io/Cloth_neXT/beta/index.json"
    DEV = "https://polyworks-art.github.io/Cloth_neXT/dev/index.json"

    @property
    def index_url(self) -> str:
        return self.value

    @property
    def label(self) -> str:
        return self.name.capitalize()


def default_channel(installed: AddonVersion) -> UpdateChannel:
    """Derive the channel from STABLE.BETA.DEV or a legacy prerelease."""
    return UpdateChannel[installed.channel_name.upper()]


class AddonUpdateState(Enum):
    NOT_CHECKED = auto()
    CHECKING = auto()
    UP_TO_DATE = auto()
    UPDATE_AVAILABLE = auto()
    SWITCH_CHANNEL = auto()
    REPOSITORY_NOT_CONFIGURED = auto()
    REPOSITORY_DISABLED = auto()
    SYNC_FAILED = auto()
    ONLINE_ACCESS_DISABLED = auto()
    INSTALL_BLOCKED = auto()
    # The handoff synchronized the repository and pointed the user at
    # Blender's native update UI. Deliberately NOT named "installing" or
    # "restart required": opening the update view proves nothing about an
    # installation — only Blender's own UI completes it.
    READY_IN_BLENDER = auto()
    UNAVAILABLE = auto()
    ERROR = auto()


class AddonUpdateSession:
    """Mutable per-Blender-session check result; holds no threads or sockets."""

    def __init__(self) -> None:
        self.reset()

    def reset(self) -> None:
        self.state = AddonUpdateState.NOT_CHECKED
        self.latest: AddonVersion | None = None
        self.message = ""
        self.decision = None
        self.migrated_channel = None


def normalized_repo_url(url: str) -> str:
    return url.strip().rstrip("/")


def find_owning_repo(repos, package_id: str, package_directory=None) -> int | None:
    """Resolve installation identity, never the selected remote feed.

    Namespaced installations must match exactly one RNA module. Source/legacy
    installs can be resolved only by their actual package directory.
    """
    from pathlib import Path
    parts = package_id.split(".")
    if len(parts) == 3 and parts[0] == "bl_ext" and parts[2] == EXTENSION_ID:
        matches = [i for i, repo in enumerate(repos)
                   if getattr(repo, "module", None) == parts[1]]
    elif package_directory is not None:
        installed = Path(package_directory).resolve()
        matches = [i for i, repo in enumerate(repos)
                   if getattr(repo, "directory", "") and
                   (Path(repo.directory) / EXTENSION_ID).resolve() == installed]
    else:
        matches = []
    return matches[0] if len(matches) == 1 else None


def configure_owning_repo(repos, package_id, channel, package_directory=None):
    """Idempotent bridge migration: change remote configuration only."""
    index = find_owning_repo(repos, package_id, package_directory)
    if index is None:
        raise ValueError("The repository owning this Cloth NeXt installation was not found.")
    repo = repos[index]
    if not getattr(repo, "directory", ""):
        raise ValueError("The owning repository has no local directory.")
    if not getattr(repo, "enabled", False):
        raise ValueError("The owning repository is disabled.")
    if normalized_repo_url(repo.remote_url) != channel.index_url:
        repo.remote_url = channel.index_url
    return str(repo.directory)


def validate_index_url(url: str) -> None:
    parts = urlsplit(url)
    if parts.scheme != "https":
        raise ValueError(f"channel index requires https, got {url!r}")
    if parts.hostname != _ALLOWED_INDEX_HOST:
        raise ValueError(f"host {parts.hostname!r} is not the Cloth NeXt "
                         "channel host")


def fetch_channel_index(channel: UpdateChannel, *, timeout: float = 15.0,
                        open_url=None) -> dict:
    """Fetch and parse the channel index.json (bounded, fixed URL only)."""
    url = channel.index_url
    validate_index_url(url)
    if open_url is None:
        def open_url(target):  # pragma: no cover - exercised in integration
            request = urllib.request.Request(
                target, headers={"User-Agent": "ClothNeXt-UpdateCheck"})
            return urllib.request.urlopen(request, timeout=timeout)  # noqa: S310
    with open_url(url) as response:
        raw = response.read(MAX_INDEX_SIZE + 1)
    if len(raw) > MAX_INDEX_SIZE:
        raise ValueError("channel index exceeds the size limit")
    payload = json.loads(raw.decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("channel index must contain a JSON object")
    return payload


def parse_index_versions(payload: dict,
                         channel: UpdateChannel) -> tuple[AddonVersion, ...]:
    """Extract this extension's versions; enforce channel content rules.

    Each feed exposes exactly its own release level. Legacy suffixed versions
    remain readable; multiple package candidates are rejected.
    """
    data = payload.get("data")
    if not isinstance(data, list):
        raise ValueError("channel index has no 'data' package list")
    versions: list[AddonVersion] = []
    seen: set[AddonVersion] = set()
    for entry in data:
        if not isinstance(entry, dict) or entry.get("id") != EXTENSION_ID:
            continue
        version = parse_version(str(entry.get("version")))
        repository_channel = channel.name.lower()
        try:
            actual = version.channel_name
        except ValueError as exc:
            raise ValueError(f"the {channel.label} channel offers invalid "
                             f"version {version}; refusing it") from exc
        allowed = allowed_release_channels(repository_channel)
        if actual not in allowed:
            raise ValueError(f"the {channel.label} repository cannot offer "
                             f"{actual} version {version}; refusing it")
        if version in seen:
            raise ValueError(f"ambiguous channel index: Cloth NeXt {version} "
                             "is listed more than once")
        archive_url = entry.get("archive_url")
        if archive_url is not None and str(version) not in str(archive_url):
            raise ValueError(f"index/archive version mismatch for Cloth NeXt "
                             f"{version}: {archive_url!r}")
        seen.add(version)
        versions.append(version)
    if len(versions) > 1:
        raise ValueError("ambiguous channel index: multiple Cloth NeXt targets")
    return tuple(versions)


@dataclass(frozen=True, slots=True)
class UpdateDecision:
    installed_version: AddonVersion
    installed_channel: str
    selected_channel: str
    target_version: AddonVersion | None
    target_channel: str | None
    same_artifact: bool
    channel_changed: bool
    version_relationship: str
    state: AddonUpdateState


def decide_update(installed, available, channel=None):
    selected = channel.name.lower() if channel else (
        available[0].channel_name if available else installed.channel_name)
    target = available[0] if len(available) == 1 else None
    relation = ("unavailable" if target is None else "equal" if target == installed
                else "newer" if target > installed else "older")
    changed = installed.channel_name != selected
    if len(available) > 1 or (target and target.channel_name != selected):
        state = AddonUpdateState.ERROR
    elif target is None:
        state = AddonUpdateState.UNAVAILABLE
    elif target == installed:
        state = AddonUpdateState.UP_TO_DATE
    elif changed:
        state = AddonUpdateState.SWITCH_CHANNEL
    elif target > installed:
        state = AddonUpdateState.UPDATE_AVAILABLE
    else:
        state = AddonUpdateState.UP_TO_DATE
    return UpdateDecision(installed, installed.channel_name, selected, target,
                          target.channel_name if target else None,
                          target == installed, changed, relation, state)


ACTIONABLE_STATES = {AddonUpdateState.UPDATE_AVAILABLE, AddonUpdateState.SWITCH_CHANNEL}


def evaluate_update(installed, available):
    decision = decide_update(installed, available)
    return decision.state, decision.target_version


def run_update_check(session: AddonUpdateSession, channel: UpdateChannel,
                     installed: AddonVersion,
                     fetch=fetch_channel_index) -> None:
    """Worker body: fetch, parse, evaluate; every failure becomes a visible
    ERROR state instead of a hang or a silent pass."""
    try:
        payload = fetch(channel)
        versions = parse_index_versions(payload, channel)
        session.decision = decide_update(installed, versions, channel)
        state, latest = session.decision.state, session.decision.target_version
        session.latest = latest
        session.message = ("The channel index lists no Cloth NeXt entry yet."
                           if state is AddonUpdateState.UNAVAILABLE else "")
        session.state = state
    except Exception as exc:  # noqa: BLE001 — the UI must see every failure
        session.latest = None
        session.message = str(exc)
        session.state = AddonUpdateState.ERROR


def release_notes_url(version: AddonVersion | None) -> str:
    """Release notes are human documentation only, never an update source."""
    del version
    return RELEASES_PAGE_URL


STATUS_LABELS = {
    AddonUpdateState.NOT_CHECKED: "Not checked",
    AddonUpdateState.CHECKING: "Checking…",
    AddonUpdateState.UP_TO_DATE: "Up to date",
    AddonUpdateState.UPDATE_AVAILABLE: "Update available",
    AddonUpdateState.SWITCH_CHANNEL: "Switch channel",
    AddonUpdateState.REPOSITORY_NOT_CONFIGURED: "Repository not configured",
    AddonUpdateState.REPOSITORY_DISABLED: "Repository disabled",
    AddonUpdateState.SYNC_FAILED: "Repository synchronization failed",
    AddonUpdateState.ONLINE_ACCESS_DISABLED: "Offline (online access disabled)",
    AddonUpdateState.INSTALL_BLOCKED: "Update blocked",
    AddonUpdateState.READY_IN_BLENDER: "Finish the update in Blender's "
                                       "extension manager",
    AddonUpdateState.UNAVAILABLE: "No update information",
    AddonUpdateState.ERROR: "Error",
}


@dataclass(frozen=True, slots=True)
class UpdateSectionView:
    status_text: str
    message: str
    show_update_handoff: bool  # "Update through Blender" — never a self-install
    show_open_extensions: bool
    show_repo_setup: bool
    check_enabled: bool


def build_section_view(state: AddonUpdateState, latest: AddonVersion | None,
                       message: str) -> UpdateSectionView:
    status_text = STATUS_LABELS[state]
    if state in ACTIONABLE_STATES and latest is not None:
        status_text = f"{status_text}: {latest}"
    show_update_handoff = state in ACTIONABLE_STATES
    if show_update_handoff and latest is not None and not message:
        message = (f"Version {latest} is available. Updates are completed "
                   "through Blender's native extension manager to avoid "
                   "replacing the running add-on.")
    return UpdateSectionView(
        status_text=status_text,
        message=message,
        show_update_handoff=show_update_handoff,
        show_open_extensions=not show_update_handoff,
        show_repo_setup=state is AddonUpdateState.REPOSITORY_NOT_CONFIGURED,
        check_enabled=state is not AddonUpdateState.CHECKING)
